version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner # Use the production stage
    image: '${DOCKER_REGISTRY_PATH}:latest'
    container_name: hi-fella-shoe-api
    restart: unless-stopped
    ports:
      - '${PORT:-8000}:8000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
